// Generated by CoffeeScript 1.8.0
(function() {
  (null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo);});

  (null_mabye).and_then(function(_ref){return new (null_mabye).constructor(_ref.foo());});

  ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo);})).and_then(function(_ref){return new ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo);})).constructor(_ref.bar);});

  ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo());})).and_then(function(_ref){return new ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo());})).constructor(_ref.bar);});

  (null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo);}).bar;

  (null_mabye).and_then(function(_ref){return new (null_mabye).constructor(_ref.foo());}).bar;

  ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo());}).bar).and_then(function(_ref){return new ((null_maybe).and_then(function(_ref){return new (null_maybe).constructor(_ref.foo());}).bar).constructor(_ref.baz);});

  (null_maybe.foo).and_then(function(_ref){return new (null_maybe.foo).constructor(_ref.bar);});

}).call(this);
